// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Produtos implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject produtosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Produtos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NM_Produto("NM_Produto"),
		DS_Produto("DS_Produto"),
		QT_Estoque("QT_Estoque"),
		VL_Preco("VL_Preco"),
		DT_Validade("DT_Validade"),
		Image("Image");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Produtos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Produtos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject produtosMendixObject)
	{
		if (produtosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, produtosMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.produtosMendixObject = produtosMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Produtos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Produtos(context, mendixObject);
	}

	public static myfirstmodule.proxies.Produtos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Produtos.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Produtos> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Produtos.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of NM_Produto
	 */
	public final java.lang.String getNM_Produto()
	{
		return getNM_Produto(getContext());
	}

	/**
	 * @param context
	 * @return value of NM_Produto
	 */
	public final java.lang.String getNM_Produto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NM_Produto.toString());
	}

	/**
	 * Set value of NM_Produto
	 * @param nm_produto
	 */
	public final void setNM_Produto(java.lang.String nm_produto)
	{
		setNM_Produto(getContext(), nm_produto);
	}

	/**
	 * Set value of NM_Produto
	 * @param context
	 * @param nm_produto
	 */
	public final void setNM_Produto(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nm_produto)
	{
		getMendixObject().setValue(context, MemberNames.NM_Produto.toString(), nm_produto);
	}

	/**
	 * @return value of DS_Produto
	 */
	public final java.lang.String getDS_Produto()
	{
		return getDS_Produto(getContext());
	}

	/**
	 * @param context
	 * @return value of DS_Produto
	 */
	public final java.lang.String getDS_Produto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DS_Produto.toString());
	}

	/**
	 * Set value of DS_Produto
	 * @param ds_produto
	 */
	public final void setDS_Produto(java.lang.String ds_produto)
	{
		setDS_Produto(getContext(), ds_produto);
	}

	/**
	 * Set value of DS_Produto
	 * @param context
	 * @param ds_produto
	 */
	public final void setDS_Produto(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ds_produto)
	{
		getMendixObject().setValue(context, MemberNames.DS_Produto.toString(), ds_produto);
	}

	/**
	 * @return value of QT_Estoque
	 */
	public final java.lang.Integer getQT_Estoque()
	{
		return getQT_Estoque(getContext());
	}

	/**
	 * @param context
	 * @return value of QT_Estoque
	 */
	public final java.lang.Integer getQT_Estoque(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.QT_Estoque.toString());
	}

	/**
	 * Set value of QT_Estoque
	 * @param qt_estoque
	 */
	public final void setQT_Estoque(java.lang.Integer qt_estoque)
	{
		setQT_Estoque(getContext(), qt_estoque);
	}

	/**
	 * Set value of QT_Estoque
	 * @param context
	 * @param qt_estoque
	 */
	public final void setQT_Estoque(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer qt_estoque)
	{
		getMendixObject().setValue(context, MemberNames.QT_Estoque.toString(), qt_estoque);
	}

	/**
	 * @return value of VL_Preco
	 */
	public final java.math.BigDecimal getVL_Preco()
	{
		return getVL_Preco(getContext());
	}

	/**
	 * @param context
	 * @return value of VL_Preco
	 */
	public final java.math.BigDecimal getVL_Preco(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.VL_Preco.toString());
	}

	/**
	 * Set value of VL_Preco
	 * @param vl_preco
	 */
	public final void setVL_Preco(java.math.BigDecimal vl_preco)
	{
		setVL_Preco(getContext(), vl_preco);
	}

	/**
	 * Set value of VL_Preco
	 * @param context
	 * @param vl_preco
	 */
	public final void setVL_Preco(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal vl_preco)
	{
		getMendixObject().setValue(context, MemberNames.VL_Preco.toString(), vl_preco);
	}

	/**
	 * @return value of DT_Validade
	 */
	public final java.util.Date getDT_Validade()
	{
		return getDT_Validade(getContext());
	}

	/**
	 * @param context
	 * @return value of DT_Validade
	 */
	public final java.util.Date getDT_Validade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DT_Validade.toString());
	}

	/**
	 * Set value of DT_Validade
	 * @param dt_validade
	 */
	public final void setDT_Validade(java.util.Date dt_validade)
	{
		setDT_Validade(getContext(), dt_validade);
	}

	/**
	 * Set value of DT_Validade
	 * @param context
	 * @param dt_validade
	 */
	public final void setDT_Validade(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dt_validade)
	{
		getMendixObject().setValue(context, MemberNames.DT_Validade.toString(), dt_validade);
	}

	/**
	 * Get value of Image
	 * @param image
	 */
	public final myfirstmodule.proxies.ENUM_Produtos getImage()
	{
		return getImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Image
	 */
	public final myfirstmodule.proxies.ENUM_Produtos getImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Image.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Produtos.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Image
	 * @param image
	 */
	public final void setImage(myfirstmodule.proxies.ENUM_Produtos image)
	{
		setImage(getContext(), image);
	}

	/**
	 * Set value of Image
	 * @param context
	 * @param image
	 */
	public final void setImage(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Produtos image)
	{
		if (image != null) {
			getMendixObject().setValue(context, MemberNames.Image.toString(), image.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Image.toString(), null);
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return produtosMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Produtos that = (myfirstmodule.proxies.Produtos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
